from django.urls import path, include
from . import views
from . import run_api

urlpatterns = [
    path('v3/', include('map_api.v3.urls')),
    path('v2/agent/runs/', run_api.run_list, name='v2_agent_runs'),
    path('v2/agent/runs/<int:run_id>/actions/', run_api.run_actions, name='v2_agent_run_actions'),
    path('v2/agent/runs/<int:run_id>/replan/', run_api.run_replan, name='v2_agent_run_replan'),
    path('v2/agent/runs/<int:run_id>/artifacts/', run_api.run_artifacts, name='v2_agent_run_artifacts'),
    path('v2/agent/runs/<int:run_id>/artifacts/<str:artifact_id>/download/', run_api.run_artifact_download, name='v2_agent_run_artifact_download'),
    path('v2/agent/runs/<int:run_id>/evidence/', run_api.run_evidence, name='v2_agent_run_evidence'),
    path('v2/agent/runs/<int:run_id>/', views.agent_run_detail, name='v2_agent_run_detail'),
    path('v2/agent/runs/<int:run_id>/events/', run_api.run_events, name='v2_agent_run_events'),
    path('v2/agent/runs/<int:run_id>/events/stream/', run_api.run_events_stream, name='v2_agent_run_events_stream'),
    path('system/health/', views.system_health, name='system_health'),
    path('system/dependencies/', views.system_dependencies, name='system_dependencies'),
    path('system/dependencies/probe/', views.system_dependencies_probe, name='system_dependencies_probe'),
    path('analysis/indices/', views.spectral_indices_catalog, name='spectral_indices_catalog'),
    path('analysis/change/', views.analysis_change, name='analysis_change'),
    path('analysis/runs/<int:run_id>/', views.analysis_run_detail, name='analysis_run_detail'),
    path('satellite/get-img/', views.get_satellite_img_api, name='get_satellite_img'),
    path('satellite/get-sentinel-img/', views.get_sentinel_img_api, name='get_sentinel_img'),
    path('satellite/show-img/', views.show_satellite_image, name='show_satellite_image'),
    path('satellite/progress/', views.get_progress, name='get_progress'),
    path('satellite/cleanup/', views.cleanup_cache, name='cleanup_cache'),
    path('imagery/search/', views.imagery_search, name='imagery_search'),
    path('imagery/recommend-source/', views.imagery_recommend_source, name='imagery_recommend_source'),
    path('imagery/scenes/', views.imagery_scene_list, name='imagery_scene_list'),
    path('imagery/scenes/<int:scene_id>/', views.imagery_scene_detail, name='imagery_scene_detail'),
    path('agent/sessions/', views.agent_session_list, name='agent_session_list'),
    path('agent/sessions/<int:session_id>/', views.agent_session_detail, name='agent_session_detail'),
    path('agent/runs/<int:run_id>/', views.agent_run_detail, name='agent_run_detail'),
    path('agent/sessions/<int:session_id>/events/', views.agent_session_events, name='agent_session_events'),
    path('agent/sessions/<int:session_id>/events/stream/', views.agent_session_events_stream, name='agent_session_events_stream'),
    path('agent/sessions/<int:session_id>/transcript/', views.agent_session_transcript, name='agent_session_transcript'),
    path('agent/sessions/<int:session_id>/messages/', views.agent_session_messages, name='agent_session_messages'),
    path('ai/query-region/', views.ai_query_region, name='ai_query_region'),
    path('ai/history/', views.chat_history_list, name='chat_history_list'),
    path('ai/history/<int:history_id>/', views.chat_history_detail, name='chat_history_detail'),
    path('geo/search/', views.geo_search, name='geo_search'),
    path('report/generate/', views.generate_report, name='generate_report'),
    path('report/download/', views.download_report, name='download_report'),
]
