# Generated by Django 5.2.13 on 2026-06-06 08:06

from django.db import migrations, models


def dedupe_history(apps, schema_editor):
    ChatHistory = apps.get_model("map_api", "ChatHistory")
    ChatHistory.objects.filter(image_file="").delete()

    seen = set()
    for item in ChatHistory.objects.order_by("-updated_at", "-id"):
        if item.image_file in seen:
            item.delete()
        else:
            seen.add(item.image_file)


class Migration(migrations.Migration):

    dependencies = [
        ("map_api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(dedupe_history, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="chathistory",
            name="image_file",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
