# Generated by Django 5.2.13 on 2026-06-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_api", "0002_alter_chathistory_image_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(default="downloading", max_length=20)),
                ("total", models.PositiveIntegerField(default=1)),
                ("done", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("min_lng", models.FloatField()),
                ("min_lat", models.FloatField()),
                ("max_lng", models.FloatField()),
                ("max_lat", models.FloatField()),
                ("gsd_m", models.FloatField(default=0)),
                ("area_km2", models.FloatField(default=0)),
                ("resolution_px", models.PositiveIntegerField(default=0)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
