# Generated by Django 5.2.13 on 2026-06-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_api", "0003_downloadtask"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageryScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, unique=True)),
                ("source", models.CharField(default="mapbox", max_length=50)),
                (
                    "source_label",
                    models.CharField(
                        default="Mapbox Satellite Basemap", max_length=120
                    ),
                ),
                (
                    "product_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("acquired_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("min_lng", models.FloatField()),
                ("min_lat", models.FloatField()),
                ("max_lng", models.FloatField()),
                ("max_lat", models.FloatField()),
                ("gsd_m", models.FloatField(default=0)),
                ("area_km2", models.FloatField(default=0)),
                ("cloud_percent", models.FloatField(blank=True, null=True)),
                (
                    "processing_level",
                    models.CharField(default="basemap", max_length=80),
                ),
                (
                    "license_type",
                    models.CharField(default="mapbox_terms", max_length=80),
                ),
                (
                    "decision_grade",
                    models.CharField(default="reference", max_length=50),
                ),
                ("limitations", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="downloadtask",
            name="scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="download_tasks",
                to="map_api.imageryscene",
            ),
        ),
    ]
