# Generated by Django 5.2.13 on 2026-06-06 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_api", "0004_imageryscene_downloadtask_scene"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_histories",
                to="map_api.imageryscene",
            ),
        ),
    ]
