# Generated by Codex on 2026-06-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_api", "0005_chathistory_scene"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("goal", models.TextField()),
                ("mode", models.CharField(default="precise", max_length=20)),
                ("status", models.CharField(default="running", max_length=30)),
                ("slots", models.JSONField(blank=True, default=dict)),
                ("plan", models.JSONField(blank=True, default=dict)),
                ("timeline", models.JSONField(blank=True, default=list)),
                ("messages", models.JSONField(blank=True, default=list)),
                ("artifacts", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_sessions",
                        to="map_api.chathistory",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_sessions",
                        to="map_api.imageryscene",
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
    ]
