# Generated by Django 5.2.13 on 2026-08-31 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0012_agentsession_owner_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.CharField(max_length=120, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('worker_claim', models.CharField(blank=True, default='', max_length=80)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to='map_api.agentsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
