# Generated by Django 5.2.13 on 2026-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0013_reportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtask',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='worker_claim',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
