# Generated by Django 5.2.13 on 2026-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0014_downloadtask_attempts_downloadtask_claimed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_key', models.CharField(max_length=80, unique=True)),
                ('tokens', models.FloatField(default=0)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('last_refill_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bucket_key'],
            },
        ),
    ]
