# Generated by Django 5.2.13 on 2026-09-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0015_apiratelimitbucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_events', to='map_api.agentsession')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['session', 'sequence'], name='map_api_exe_session_654ad3_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence'), name='uniq_agent_event_sequence')],
            },
        ),
    ]
