# Generated by Django 5.2.13 on 2026-09-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0016_executionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('status', models.CharField(default='running', max_length=20)),
                ('scene_ids', models.JSONField(blank=True, default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('model_versions', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
