# Generated by Django 5.2.13 on 2026-09-05 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0017_analysisrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=40)),
                ('file_path', models.CharField(max_length=500)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('bands', models.JSONField(blank=True, default=list)),
                ('resolution_m', models.FloatField(blank=True, null=True)),
                ('nodata_ratio', models.FloatField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raster_assets', to='map_api.imageryscene')),
            ],
        ),
    ]
