# Generated by Django 5.2.13 on 2026-09-05 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0018_rasterasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, default='', max_length=30)),
                ('source_method', models.CharField(blank=True, default='', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='map_api.analysisrun')),
            ],
        ),
    ]
