# Generated by Django 5.2.13 on 2026-09-05 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0019_finding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(max_length=40)),
                ('crop_file', models.CharField(blank=True, default='', max_length=500)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('metric', models.CharField(blank=True, default='', max_length=80)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_api.rasterasset')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='map_api.finding')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_api.imageryscene')),
            ],
        ),
    ]
