# Generated by Django 5.2.13 on 2026-09-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0021_externalservicehealth_observability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('run_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(default='queued', max_length=40)),
                ('mode', models.CharField(default='precise', max_length=30)),
                ('current_step_id', models.CharField(blank=True, default='', max_length=120)),
                ('plan_version', models.PositiveIntegerField(default=1)),
                ('context_version', models.PositiveIntegerField(default=1)),
                ('provider', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.CharField(max_length=160)),
                ('kind', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=240)),
                ('uri', models.CharField(max_length=500)),
                ('preview_uri', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_v2', to='map_api.agentrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'artifact_id'), name='uniq_run_artifact')],
            },
        ),
        migrations.CreateModel(
            name='RunCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('state_snapshot', models.JSONField(default=dict)),
                ('context_snapshot', models.JSONField(default=dict)),
                ('plan_snapshot', models.JSONField(default=dict)),
                ('last_event_sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='map_api.agentrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_run_checkpoint')],
            },
        ),
        migrations.CreateModel(
            name='RunEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=160)),
                ('kind', models.CharField(max_length=60)),
                ('scene_id', models.CharField(blank=True, default='', max_length=160)),
                ('asset_id', models.CharField(blank=True, default='', max_length=160)),
                ('metric', models.CharField(blank=True, default='', max_length=120)),
                ('value', models.JSONField(blank=True, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=240)),
                ('aoi', models.JSONField(blank=True, null=True)),
                ('mask_statistics', models.JSONField(blank=True, default=dict)),
                ('data_contract', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_v2', to='map_api.agentrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'evidence_id'), name='uniq_run_evidence')],
            },
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('status', models.CharField(default='queued', max_length=40)),
                ('depends_on', models.JSONField(blank=True, default=list)),
                ('required_capabilities', models.JSONField(blank=True, default=list)),
                ('input_refs', models.JSONField(blank=True, default=list)),
                ('output_refs', models.JSONField(blank=True, default=list)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('approval_policy', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='map_api.agentrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'step_id'), name='uniq_run_step')],
            },
        ),
    ]
