# Generated by Django 5.2.13 on 2026-09-08 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0022_agentrun_runartifact_runcheckpoint_runevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='event_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(max_length=60)),
                ('step_id', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('refs', models.JSONField(default=list)),
                ('command_key', models.CharField(max_length=160)),
                ('command_digest', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='map_api.agentrun')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_run_event_sequence'), models.UniqueConstraint(fields=('run', 'command_key'), name='uniq_run_event_command')],
            },
        ),
    ]
