# Generated by Django 5.2.13 on 2026-09-08 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0023_agentrun_event_sequence_runevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('step_id', models.CharField(max_length=120)),
                ('arguments', models.JSONField(default=dict)),
                ('inputs', models.JSONField(default=dict)),
                ('status', models.CharField(default='running', max_length=30)),
                ('result', models.JSONField(default=dict)),
                ('context_patch', models.JSONField(default=dict)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('claim', models.CharField(max_length=64)),
                ('lease_until', models.DateTimeField()),
                ('error', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='map_api.agentrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'call_key'), name='uniq_run_tool_call')],
            },
        ),
    ]
