# Generated by Django 5.2.13 on 2026-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0024_runtoolcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='cancellation_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='execution_engine',
            field=models.CharField(default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='runstep',
            name='allow_replan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runstep',
            name='completion_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='runstep',
            name='failure_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='runstep',
            name='lease_cancellation_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runstep',
            name='lease_plan_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runstep',
            name='lease_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='runstep',
            name='lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runstep',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runstep',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
