# Generated by Django 5.2.13 on 2026-09-11 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0025_run_step_leases'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='budget',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='usage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='worker_claim',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_session_key', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(default='新的影像问答', max_length=200)),
                ('event_sequence', models.PositiveIntegerField(default=0)),
                ('context_version', models.PositiveIntegerField(default=1)),
                ('workspace', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('archived', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_conversations', to='map_api.agentrun')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='map_api.conversation'),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('parts', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='queued', max_length=30)),
                ('delivery', models.CharField(default='steer', max_length=20)),
                ('sequence', models.PositiveIntegerField()),
                ('request_id', models.CharField(max_length=120)),
                ('request_digest', models.CharField(max_length=64)),
                ('context_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='map_api.conversation')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='map_api.agentrun')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='trigger_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_runs', to='map_api.conversationmessage'),
        ),
        migrations.CreateModel(
            name='SpatialAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_session_key', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=240)),
                ('kind', models.CharField(default='image', max_length=30)),
                ('status', models.CharField(default='uploading', max_length=30)),
                ('coordinate_space', models.CharField(default='image_pixels', max_length=30)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('preview_path', models.CharField(blank=True, default='', max_length=500)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('crs', models.CharField(blank=True, default='', max_length=120)),
                ('transform', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('processing_claim', models.CharField(blank=True, default='', max_length=64)),
                ('processing_lease_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='map_api.conversation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='map_api.spatialattachment')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_v3', to='map_api.imageryscene')),
            ],
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='messages', to='map_api.spatialattachment'),
        ),
        migrations.CreateModel(
            name='AttachmentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_bytes', models.BigIntegerField()),
                ('chunk_size', models.PositiveIntegerField(default=1048576)),
                ('received_chunks', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='uploading', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='map_api.spatialattachment')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('kind', models.CharField(default='window', max_length=40)),
                ('window', models.JSONField(default=list)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('preview_path', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('context_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='map_api.spatialattachment')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='map_api.conversation')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='map_api.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('context_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='started', max_length=30)),
                ('decision', models.JSONField(default=dict)),
                ('usage', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='map_api.agentrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'number'), name='v3_turn_number')],
            },
        ),
        migrations.CreateModel(
            name='ConversationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='map_api.conversation')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'sequence'), name='v3_event_sequence')],
            },
        ),
        migrations.CreateModel(
            name='LegacyConversationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model', models.CharField(max_length=40)),
                ('source_pk', models.PositiveIntegerField()),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_links', to='map_api.conversation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_model', 'source_pk'), name='v3_legacy_link')],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'request_id'), name='v3_message_request'),
        ),
        migrations.AddConstraint(
            model_name='conversationmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='v3_message_sequence'),
        ),
    ]
